library/urls.py
from django.urls import path, include

from . import views

app_name = 'library'
urlpatterns = [
    path('', views.index, name='index'),
    path('library/', views.index, name='index'),
    path('library/<int:page>/', views.index, name='index'),
    path('library/book-<bookid>/', views.bookdetails, name='bookdetails'),
    path('library/book-<bookid>/review/write', views.write_review, name='writereview'),
    path('library/book-<bookid>/rate/<int:rating>/', views.ratebook, name='ratebook'),
    path('library/book-<bookid>/buy/', views.buy_book, name='buy_book'),
    path('library/book-<bookid>/recommend/', views.recommend_book, name='recommend_book'),
    path('library/book-<bookid>/delete/', views.delete_book, name='delete_book'),
    path('library/book-<bookid>/acceptpublication/', views.accept_publication, name='accept_publication'),
    path('library/book-<bookid>/rejectpublication/', views.reject_publication, name='reject_publication'),
    path('library/book-<bookid>/review-<int:reviewid>/delete/', views.delete_review, name='delete_review'),
    path('library/book-<bookid>/review-<int:reviewid>/report/', views.report_review, name='report_review'),
    path('library/book-<bookid>/review-<int:reviewid>/vote/<vote>/', views.vote_review, name='vote_review'),
    path('library/book-<bookid>/review-<int:reviewid>/comment/', views.comment_review, name='comment_review'),
    path('library/book-<bookid>/review-<int:reviewid>/', views.review_details, name='review_details'),
    path('account/', include('django.contrib.auth.urls')),
    path('account/moderation/requests/publisher/', views.modo_publisher_requests, name='publisher_requests'),
    path('account/moderation/requests/publication/', views.modo_publication_requests, name='publication_requests'),
    path('account/moderation/requests/report/', views.modo_review_reports, name='review_reports'),
    path('account/signup/', views.SignUp.as_view(), name='signup'),
    path('account/profile/<user>/', views.profile, name='profile'),
    path('account/profile/<user>/update/', views.CustomUserUpdate.as_view(), name='update_profile'),
    path('account/profile/<user>/publisherrequest/', views.request_publisher, name='request_publisher'),
    path('account/profile/<user>/request/', views.send_friend_request, name='send_friend_request'),
    path('account/profile/<user>/request/accept', views.accept_friend_request, name='accept_friend_request'),
    path('account/profile/<user>/request/reject', views.reject_friend_request, name='reject_friend_request'),
    path('account/profile/<user>/request/delete', views.delete_friend, name='delete_friend'),
    path('account/profile/<user>/balance/', views.incr_balance, name='incr_balance'),
    path('account/profile/<user>/books/', views.user_books, name='user_books'),
    path('account/profile/<user>/publishedbooks/', views.user_published_books, name='user_published_books'),
    path('account/profile/<user>/publishedbooks/new', views.publish_book, name='publish_book'),
    path('account/profile/<user>/friends/', views.user_friends, name='user_friends'),
    path('account/profile/<user>/recommendations/', views.user_recommendations, name='user_recommendations'),
    path('account/profile/<user>/block/', views.block_user, name='block_user'),
    path('account/profile/<user>/unblock/', views.unblock_user, name='unblock_user'),
    path('account/profile/<user>/publisherrequest/accept', views.accept_publisher_request, name='accept_publisher_request'),
    path('account/profile/<user>/publisherrequest/reject', views.reject_publisher_request, name='reject_publisher_request'),
]

online_library/urls.py
from django.contrib import admin
from django.urls import include, path


app_name = 'online_library'
urlpatterns = [
    path('', include('library.urls')),
    path('admin/', admin.site.urls),
]

library/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.core.validators import RegexValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.urls import reverse, reverse_lazy



class CustomUser(AbstractUser):
    name_validator = RegexValidator(
        regex='^([a-zA-ZÀ-ÿ-.]|[a-zA-ZÀ-ÿ] [a-zA-ZÀ-ÿ])+$',
        message='This is not a valid name'
    )
    address_validator = RegexValidator(
        regex='^([a-zA-Z0-9À-ÿ -"\'.,;:&()])+$',
        message='This is not a valid address'
    )

    AUTHORIZATION_LEVEL_CHOICES = (
        (0, 'Blocked'),
        (1, 'Basic User'),
        (2, 'Publisher waiting for approval'),
        (3, 'Publisher'),
        (4, 'Moderator'),
    )
    PRIVACY_LEVEL_CHOICES = (
        (0, 'Profile open to anyone'),
        (1, 'Profile hidden to visitors'),
        (2, 'Profile hidden to everyone'),
    )

    first_name = models.CharField(blank=False, max_length=30, validators=[name_validator])
    last_name = models.CharField(blank=False, max_length=150, validators=[name_validator])
    address = models.CharField(blank=False, max_length=300, validators=[address_validator])
    email = models.CharField(blank=False, max_length=150)
    birthday = models.DateField()

    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    books = models.ManyToManyField('Book')
    friends = models.ManyToManyField('self', through='Friendship', related_name='friendship', symmetrical=False)
    book_recommendations = models.ManyToManyField('self', related_name='book_recommendation', through='Recommendation', symmetrical=False)

    authorization_level = models.IntegerField(choices=AUTHORIZATION_LEVEL_CHOICES, default=1)
    privacy_level = models.IntegerField(choices=PRIVACY_LEVEL_CHOICES, default=0)

    def __str__(self):
        return self.first_name + " " + self.last_name + " (" + self.username + ")"

    def get_absolute_url(self):
        return reverse('library:profile', kwargs={'user':self.username})


class Friendship(models.Model):
    def clean(self):
        super(Friendship, self).clean()
        if self.sender == self.target:
            raise ValidationError("A user cannot be friend with himself.")

    def save(self, *args, **kwargs):
        self.full_clean()
        return super(Friendship, self).save(*args, **kwargs)

    FRIEND_STATUS_CHOICES = (
        (0, 'Waiting for approval'),
        (1, 'Accepted'),
    )

    sender = models.ForeignKey('CustomUser', related_name='sender', on_delete=models.CASCADE)
    target = models.ForeignKey('CustomUser', related_name='target', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=FRIEND_STATUS_CHOICES, default=0)

    class Meta:
        unique_together = ('sender', 'target')

    def __str__(self):
        if self.status == 0:
            status_str = "Waiting for approval"
        else:
            status_str = "Accepted"
        return str(self.sender) + " -> " + str(self.target) + " | " + status_str


class Recommendation(models.Model):
    sender = models.ForeignKey('CustomUser', related_name='r_sender', on_delete=models.CASCADE)
    target = models.ForeignKey('CustomUser', related_name='r_target', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey('Book', on_delete=models.CASCADE)
    # TODO add a message with the recommendation

    def __str__(self):
        return str(self.sender) + " -> " + str(self.target) + " | " + str(self.book)



class Category(models.Model):
    """
    Category model
    """

    name = models.CharField(blank=False, max_length=20, unique=True)

    def __str__(self):
        return self.name



class Rating(models.Model):
    """
    Rating model
    """

    EVALUATION_CHOICES = [(i, i) for i in range(6)]

    date = models.DateTimeField(auto_now_add=True)
    evaluation = models.IntegerField(choices=EVALUATION_CHOICES)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    book = models.ForeignKey('Book', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'book')

    def __str__(self):
        return str(self.user) + " | " + str(self.book) + " | " + str(self.evaluation) + "/5"




class Review(models.Model):
    """
    Review model
    """

    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField('review', blank=False, max_length=5000)
    summary = models.CharField(blank=True, max_length=140)
    nb_likes = models.PositiveIntegerField('likes', default=0)
    nb_dislikes = models.PositiveIntegerField('dislikes', default=0)
    nb_reports = models.PositiveIntegerField('reports', default=0)
    voters = models.ManyToManyField('CustomUser')
    associated_rating = models.OneToOneField('Rating', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.associated_rating) + " | likes/dislikes: " + str(self.nb_likes) + "/" + str(self.nb_dislikes) + " | Review (" + str(len(self.content)) + " chars), summary: " + self.summary






class Comment(models.Model):
    """
    Comment model
    """

    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField('comment', blank=False, max_length=1000)
    parent_review = models.ForeignKey('Review', on_delete=models.CASCADE)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) + " | likes/dislikes: " + str(self.nb_likes) + "/" + str(self.nb_dislikes) + " | " + self.content



class Book(models.Model):
    """
    Book model
    """

    BOOK_STATUS_CHOICES = (
        (0, 'Waiting for approval'),
        (1, 'Published'),
        (2, 'Removed'),
    )
    YEAR_CHOICES = []
    for y in range(datetime.datetime.now().year, 1900, -1):
        YEAR_CHOICES.append((y, y))

    ISBN_VALIDATOR = RegexValidator(
        '^([0-9]{3}-)?[0-9]-[0-9]{4}-[0-9]{4}-[0-9]$',
        'The ISBN has an invalid format'
    )
    IMAGE_URL_VALIDATOR = RegexValidator(
        '^(http(s)?:\/\/)?(www\.)?[a-zA-Z0-9\_\-\.]+([\-\.\/]{1}[a-zA-Z0-9\_\-\%\.]+)*\.(jpg|jpeg|png)$',
        'The image URL has an invalid format'
    )
    def AUTHOR_VALIDATOR(user):
        if not True:                                                                                    # TODO assert user is author
            raise ValidationError(
                _('User %(name)s is not an author and does not have permission to publish a book.'),
                params={'name': user.name}
            )

    isbn = models.CharField(
        'ISBN',
        primary_key=True,
        unique=True,
        help_text='ISBN format: either <em>X-XXXX-XXXX-X</em> or <em>XXX-X-XXXX-XXXX-X</em> where X is a digit',
        max_length=17,
        validators=[ISBN_VALIDATOR]
    )
    status = models.IntegerField(default=0, choices=BOOK_STATUS_CHOICES)
    title = models.CharField(blank=False, max_length=100)
    author = models.ForeignKey('CustomUser', on_delete=models.PROTECT, validators=[AUTHOR_VALIDATOR], blank=True, null=True)
    author_pseudonym = models.CharField(blank=False, max_length=50)
    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(0.0, 'The price must be positive.')])
    year_of_pub = models.IntegerField('year of publication', choices=YEAR_CHOICES)
    image_url = models.URLField(
        max_length=1000,
        help_text='Image format should be .jpg, .jpeg or .png',
        validators=[IMAGE_URL_VALIDATOR]
    )
    category = models.ForeignKey('Category', on_delete=models.PROTECT)

    def __str__(self):
        return self.title + " (" + self.category.name + ") by " + self.author_pseudonym + " (" + str(self.year_of_pub) + ") - $" + str(self.price)

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

from django.utils import timezone



class LoginForm(forms.Form):
    username = forms.CharField(label='User', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, max_length=100)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        widgets = {
          'birthday': forms.DateInput(attrs={'type': 'date'}),
        }
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name',
                  'email', 'address', 'birthday']

class BuyBookForm(forms.Form):
    pass

class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['isbn', 'title', 'author_pseudonym', 'price', 'year_of_pub', 'image_url', 'category']

class RecommendBookForm(forms.Form):
    def __init__(self, *args, **kwargs):
        friends_choices = kwargs.pop('friends', None)
        super(RecommendBookForm, self).__init__(*args, **kwargs)
        self.fields['friend'] = forms.ChoiceField(
            required=True,
            label='Who do you want to recommend this book to?',
            choices = friends_choices,
        )

class WriteReviewForm(forms.Form):
    def __init__(self, *args, **kwargs):
        default_eval = kwargs.pop('default_eval', None)
        super(WriteReviewForm, self).__init__(*args, **kwargs)

        self.fields['evaluation'] = forms.ChoiceField(
            required=True,
            choices=[(i, i) for i in range(1, 6)],
            initial=default_eval,
        )
        self.fields['summary'] = forms.CharField(
            required=True,
            max_length=140,
            label='Summary or title for the review',
            help_text='Max. 140 characters',
        )
        self.fields['content'] = forms.CharField(
            required=True,
            max_length=5000,
            widget=forms.Textarea,
            help_text='Max. 5000 characters',
        )

class WriteCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

library/templates/library/book.html
{% extends "library/base.html" %}


{% block title %}{{ book.title }}{% endblock %}

{% block content %}

<h2 id="page-title">Book Details</h2>

<div id="data_content">
  {% if owns_book %}
    <p class="emph" style="text-align:center">You have bought this book.</p>
    <p style="text-align:center"><a href="{% url 'library:user_books' user=user.username %}">Go to your books</a></p>
  {% endif %}
  <div id="book_details">
    <img id="cover" src="{{ book.image_url }}" alt="Cover of {{ book.title }}"/>
    <div id="book_data">
      <p>
        <span class="emph">Title:</span>
        <span id="title">{{ book.title }}</span>
      </p>
      <p>
        <span class="emph">Author:</span>
        {% if book.author.username %}
          <span class="author"><a class="hov" href="{% url 'library:profile' user=book.author.username %}">{{ book.author_pseudonym }}</a></span>
        {% else %}
          <span class="author">{{ book.author_pseudonym }}</span>
        {% endif %}
      </p>
      <p>
        <span class="emph">Price:</span>
        <span id="price">${{ book.price }}</span>
      </p>
      <br/>
      <p>
        <span class="emph">Category:</span>
        <span id="category">{{ book.category }}</span>
      </p>
      <p>
        <span class="emph">Published in:</span>
        <span id="year_of_pub">{{ book.year_of_pub }}</span>
      </p>
      <p>
        <span class="emph">ISBN:</span>
        <span id="isbn">{{ book.isbn }}</span>
      </p>
      <br/>
      <p>
        <span class="emph">Bought</span>
        <span id="nb_bought">{{ nb_times_bought }}</span>
          <span class="emph">time{% if nb_times_bought > 1 %}s{% endif %}</span>
      </p>
      <p>
        {% if nb_ratings > 0 %}
          <span class="emph">Rated</span>
          <span id="avg_rating">{{ avg_rating }}/5</span>
          <span class="emph">out of</span>
          <span id="nb_ratings">{{ nb_ratings }}</span>
          {% if nb_ratings > 1 %}
            <span class="emph">ratings</span>
          {% else %}
            <span class="emph">rating</span>
          {% endif %}
        {% else %}
          <span class="emph">Not rated yet</span>
        {% endif %}
      </p>
      <p>
        {% if nb_reviews > 0 %}
          {% if nb_reviews > 1 %}
            <span id="nb_reviews">{{ nb_reviews }}</span>
            <span class="emph">reviews</span>
          {% else %}
            <span id="nb_reviews">1</span>
            <span class="emph">review</span>
          {% endif %}
        {% else %}
          <span class="emph">Not reviewed yet</span>
        {% endif %}
      </p>
      <br/>
      {% if user.is_authenticated %}
        <p><a class="hov" href="{% url 'library:writereview' bookid=book.pk %}">Write a review</a></p>
        <p style="margin:0"><span class="emph">Your rating:</span></p>
        <div class="rate">
          <input {% if usr_rating == 5 %}checked="checked"{% endif %} type="radio" id="star5" name="rate" value="5" />
          <label for="star5" title="Rate 5 stars"><a href="{% url 'library:ratebook' bookid=book.pk rating=5 %}">★</a> </label>
          <input {% if usr_rating == 4 %}checked="checked"{% endif %} src="{% url 'library:ratebook' bookid=book.pk rating=4 %}" type="radio" id="star4" name="rate" value="4" />
          <label for="star4" title="Rate 4 stars"><a href="{% url 'library:ratebook' bookid=book.pk rating=4 %}">★</a> </label>
          <input {% if usr_rating == 3 %}checked="checked"{% endif %} src="{% url 'library:ratebook' bookid=book.pk rating=3 %}" type="radio" id="star3" name="rate" value="3" />
          <label for="star3" title="Rate 3 stars"><a href="{% url 'library:ratebook' bookid=book.pk rating=3 %}">★</a>  </label>
          <input {% if usr_rating == 2 %}checked="checked"{% endif %} src="{% url 'library:ratebook' bookid=book.pk rating=2 %}" type="radio" id="star2" name="rate" value="2" />
          <label for="star2" title="Rate 2 stars"><a href="{% url 'library:ratebook' bookid=book.pk rating=2 %}">★</a>  </label>
          <input {% if usr_rating == 1 %}checked="checked"{% endif %} src="{% url 'library:ratebook' bookid=book.pk rating=1 %}" type="radio" id="star1" name="rate" value="1" />
          <label for="star1" title="Rate 1 star"><a href="{% url 'library:ratebook' bookid=book.pk rating=1 %}">★</a>  </label>
        </div>
        <div style="clear:both"></div>
      {% endif %}
    </div>
    <div style="clear:both;"></div>
    {% if user.is_authenticated %}
      <p id="actions">
        {% if not owns_book %}
          <a class="hov" href="{% url 'library:buy_book' bookid=book.pk %}">Buy</a>
        {% else %}
          <a class="hov" href="{% url 'library:recommend_book' bookid=book.pk %}">Recommend to a friend</a>
        {% endif %}
        {% if user.authorization_level == 4 %}
          <a class="hov" href="{% url 'library:delete_book' bookid=book.pk %}">Delete book</a>
        {% endif %}
      </p>
    {% endif %}
    {% if nb_reviews > 0 %}
      <div id="reviews">
        <h3 class="emph">{{ nb_reviews }} review{% if nb_reviews > 1 %}s{% endif %} of this book</h3>
        {% for review in reviews %}
          <div class="review">
            <p style="float:left">
              Review by
              <a href="{% url 'library:profile' user=review.associated_rating.user.username %}">{{ review.associated_rating.user.username }}</a>
              posted on {{ review.date }}<br>
              Evaluation: {{ review.associated_rating.evaluation }}/5
            </p>
            <p style="float:right">
              <a href="{% url 'library:vote_review' reviewid=review.pk bookid=review.associated_rating.book.pk vote='up' %}"><span style="color:green">{{ review.nb_likes }}&#128077;</span></a> |
              <a href="{% url 'library:vote_review' reviewid=review.pk bookid=review.associated_rating.book.pk vote='down' %}"><span style="color:red">{{ review.nb_dislikes }}&#128078;</span></a> |
              <span style="color:blue">{{ review.comment_set.count }}	&#128172;</span>
            </p>
            <p style="clear:both">{{ review.summary }}</p>
            <p>
              <a href="{% url 'library:review_details' bookid=book.pk reviewid=review.pk %}">Read more</a>
              {% if user.authorization_level == 4 or review.associated_rating.user == user %}
                <a style="float:right" href="{% url 'library:delete_review' bookid=book.pk reviewid=review.pk %}">Delete review</a>
              {% else %}
                <a style="float:right" href="{% url 'library:report_review' bookid=book.pk reviewid=review.pk %}">Report review</a>
              {% endif %}
            </p>
            <p style="clear:both"></p>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>




{% endblock %}

library/templates/library/create_book.html
{% extends 'library/base.html' %}

{% block title %}Publish a book{% endblock %}

{% block content %}


<h2 id="page-title">Publish a book</h2>


<div id="data_content">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publish</button>
  </form>
</div>
{% endblock %}

library/templates/library/modo_review_reports.html
{% extends "library/base.html" %}


{% block title %}Review reports{% endblock %}

{% block content %}



<h2 id="page-title">Review reports</h2>



<div id="data_content">

  {% if requests %}
    <ul>
    {% for req in requests %}
        <li>
          <a href="{% url 'library:review_details' reviewid=req.pk bookid=req.associated_rating.book.pk %}">{{ req }}, <b>{{ req.nb_reports }} reports</b></a>
        </li>
    {% endfor %}
    </ul>

  {% else %}
      <p>No report to show.</p>
  {% endif %}


</div>

{% endblock %}

library/templates/library/profile.html
{% extends "library/base.html" %}


{% block title %}{{ usr.username }}'s profile{% endblock %}

{% block content %}



<h2 id="page-title">{{ usr.username }}'s profile</h2>


<div id="data_content">
  {% if usr.privacy_level == 0 or usr.privacy_level == 1 and user.is_authenticated or usr.privacy_level == 2 and user.authorization_level == 4 %}
    {% if own_profile %}
      <p>
        <a href="{% url 'library:update_profile' user=user.username %}">Update your profile</a>
      </p>
      <p>
        {% if usr.authorization_level == 0 %}
          You have been blocked. You cannot post content anymore.
        {% endif %}
        {% if usr.authorization_level == 1 %}
          <a href="{% url 'library:request_publisher' user=usr.username %}">I want to be able to publish books.</a>
        {% endif %}
        {% if usr.authorization_level == 2 %}
          You have sent a request to become a publisher.
        {% endif %}
        {% if usr.authorization_level == 3 %}
          You are a publisher.
        {% endif %}
        {% if usr.authorization_level == 4 %}
          You are a moderator.
        {% endif %}
      </p><br>
    {% else %}
      {% if user.authorization_level == 4 %}
        <p>
          <p>
            {% if usr.authorization_level == 0 %}
              This user has been blocked. <a href="{% url 'library:unblock_user' user=usr.username %}">Unblock them.</a>
            {% else %}
              <a href="{% url 'library:block_user' user=usr.username %}">Block this user</a>
            {% endif %}
          </p>
          {% if usr.authorization_level == 2 %}
            This user sent a request to become a publisher.
            <a href="{% url 'library:accept_publisher_request' user=usr.username %}">Accept it</a>
            or <a href="{% url 'library:reject_publisher_request' user=usr.username %}">reject it</a>.
          {% endif %}
          {% if usr.authorization_level == 3 %}
            This user is a publisher.
          {% endif %}
          {% if usr.authorization_level == 4 %}
            This user is a moderator.
          {% endif %}
        </p><br>
      {% endif %}
    {% endif %}

    {% if friend_status == 1 %}
      <p>You are friend with this user.</p><br>
    {% endif %}
    {% if friend_status == 2 %}
      <p>You have sent a friend request to this user.</p><br>
    {% endif %}
    {% if friend_status == 3 %}
      <p>This user has sent you a friend request.
        <a href="{% url 'library:accept_friend_request' user=usr.username %}">Accept it</a>
        or <a href="{% url 'library:reject_friend_request' user=usr.username %}">reject it</a>.</p><br>
    {% endif %}
    {% if friend_status == 4 %}
      <p><a href="{% url 'library:send_friend_request' user=usr.username %}">Send a friend request</a></p><br>
    {% endif %}

    <p><span class="emph">Name:</span> {{ usr.first_name }} {{ usr.last_name }}</p>
    <p><span class="emph">Email:</span> {{ usr.email }}</p>
    <p><span class="emph">Date of birth:</span> {{ usr.birthday }}</p>
    {% if own_profile %}
      <p><span class="emph">Address:</span> {{ usr.address }}</p>
      <p><span class="emph">Balance:</span> ${{ usr.balance }} <a href="{% url 'library:incr_balance' user=usr.username %}">[+]</a></p>

      <br>
      <p><a href="{% url 'library:user_books' user=usr.username %}">Your books</a></p>

      {% if usr.authorization_level >= 3 %}
        <p><a href="{% url 'library:user_published_books' user=usr.username %}">Your published books</a>
          | <a href="{% url 'library:publish_book' user=usr.username %}">Publish a book</a></p>
        <p>
      {% endif %}
        <p>
          <a href="{% url 'library:user_recommendations' user=user.username %}">Your book recommendations</a>
          {% if nb_recommendations > 0 %}
            ({{ nb_recommendations }} recommendation{% if nb_recommendations > 1 %}s{% endif %})
          {% endif %}
        </p>
        <p>
          <a href="{% url 'library:user_friends' user=user.username %}">Your friends</a>
          {% if nb_friend_requests > 0 %}
            ({{ nb_friend_requests }} pending friend request{% if nb_friend_requests > 1 %}s{% endif %})
          {% endif %}
        </p>
      </p>
      {% if user.authorization_level == 4 %}
      <br>
      <p>
        <p><a href="{% url 'library:publisher_requests' %}">Publisher requests</a> ({{ nb_publisher_req }} pending)</p>
        <p><a href="{% url 'library:publication_requests' %}">Book publication requests</a> ({{ nb_publication_req }} pending)</p>
        <p><a href="{% url 'library:review_reports' %}">Reported reviews</a> ({{ nb_reports }} pending)</p>
      </p>
      {% endif %}
    {% else %}
      <br><p><a href="{% url 'library:user_books' user=usr.username %}">Their books</a></p>
      <p><a href="{% url 'library:user_published_books' user=usr.username %}">Their published books</a></p>
    {% endif %}
  {% else %}
    <p>You don't have permission to access this page.</p>
  {% endif %}
</div>

{% endblock %}

library/templates/library/review_details.html
{% extends 'library/base.html' %}

{% block title %}Review by {{ review.associated_rating.user }}{% endblock %}

{% block content %}


<h2 id="page-title">Review by {{ review.associated_rating.user }}</h2>


<div id="data_content">
  <p><a href="{% url 'library:bookdetails' bookid=bookid %}">Go back to the book</a></p>
  Review by
  <a href="{% url 'library:profile' user=review.associated_rating.user.username %}">{{ review.associated_rating.user.username }}</a>
  posted on {{ review.date }}<br>
  Evaluation: {{ review.associated_rating.evaluation }}/5
  <p style="float:right">
    <a href="{% url 'library:vote_review' reviewid=review.pk bookid=review.associated_rating.book.pk vote='up' %}"><span style="color:green">{{ review.nb_likes }}&#128077;</span></a> |
    <a href="{% url 'library:vote_review' reviewid=review.pk bookid=review.associated_rating.book.pk vote='down' %}"><span style="color:red">{{ review.nb_dislikes }}&#128078;</span></a> |
    <span style="color:blue">{{ review.comment_set.count }}	&#128172;</span>
  </p>
  <h3 style="clear:both">{{ review.summary }}</h3>
  <p>{{ review.content }}</p>
  <p style="float:right">
    <a href="{% url 'library:comment_review' bookid=bookid reviewid=review.pk %}">Comment</a> |
    {% if user.authorization_level == 4 or review.associated_rating.user == user %}
      <a href="{% url 'library:delete_review' bookid=bookid reviewid=review.pk %}">Delete review</a>
    {% else %}
      <a href="{% url 'library:report_review' bookid=bookid reviewid=review.pk %}">Report review</a>
    {% endif %}
  </p>
  <p style="clear:both"></p>
  <hr>
  <h2>{{ review.comment_set.count }} comments</h2>
  {% for c in review.comment_set.all %}
    <p>
      by
      <a href="{% url 'library:profile' user=review.associated_rating.user.username %}">{{ c.parent_review.associated_rating.user.username }}</a>
      on {{ c.date }}<br>
      <p style="margin-left:10px">{{ c.content }}</p>
    </p>
  {% endfor %}
</div>
{% endblock %}